name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Breaking Changes 🛠'
    labels:
      - 'Breaking change'
  - title: 'New Features 💎'
    labels:
      - 'Feature'
  - title: 'Fixes ⛑️'
    labels:
      - 'Fix'
  - title: 'Other Changes 🖇️'
    labels:
      - '*'
template: |
  ## Changes
  
  $CHANGES
