name-template: 'Adyen .net API Library $RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
version-resolver:
  major:
    labels:
      - 'Breaking change'
  minor:
    labels:
      - 'Feature'
  patch:
    labels:
      - 'Fix'
      - '*'
  default: patch
template: |
