name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Breaking Changes 🛠'
    labels:
      - 'Breaking change'
  - title: 'New Features 💎'
    labels:
      - 'Feature'
  - title: 'Fixes ⛑️'
    labels:
      - 'Fix'
  - title: 'Other Changes 🖇️'
    labels:
      - '*'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'Breaking change'
  minor:
    labels:
      - 'Feature'
  patch:
    labels:
      - 'Fix'
      - '*'
  default: patch
template: |
  ## Changes
  
  $CHANGES
