name-template: 'Adyen .net API Library $RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: Breaking Changes 🛠
    label:
      - Breaking change
  - title: New Features 💎
    label:
      - Feature
  - title: Fixes ⛑️
    label:
      - Fix
  - title: Other Changes 🖇️
    labels:
      - "*"

version-resolver:
  major:
    label:
      - Breaking change
  minor:
    label:
      - Feature
  patch:
    labels:
      - Fix
      - "*"
  default: patch
template: |
  ## What's Changed

  $CHANGES
  
  ## New Contributors
  
  $CONTRIBUTORS
