name-template: 'Adyen .net API Library $RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: Breaking Changes 🛠
    labels:
      - Breaking change
  - title: New Features 💎
    labels:
      - Feature
  - title: Fixes ⛑️
    labels:
      - Fix
  - title: Other Changes 🖇️
    labels:
      - "*"

version-resolver:
  major:
    labels:
      - Breaking change
  minor:
    labels:
      - Feature
  patch:
    labels:
      - Fix
      - "*"
  default: patch
template: |
  ## Changes

  $CHANGES
